# Generated by Django 2.1.2 on 2018-10-21 15:34

import django.db.models.deletion
import django_intenum
from django.conf import settings
from django.db import migrations, models

import hsreplaynet.features.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureInviteAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=hsreplaynet.features.models.get_coupon_code, max_length=32, unique=True)),
                ('redeemed_on', models.DateTimeField(blank=True, null=True)),
                ('invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='features.FeatureInvite')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature invite alias',
                'verbose_name_plural': 'Feature invite aliases',
            },
            bases=(models.Model, hsreplaynet.features.models.Redeemable),
        ),
    ]
