/**
 * RedshiftFilterEnums
 */

export const enum TimeRange {
	CURRENT_SEASON = "CURRENT_SEASON",
	LAST_1_DAY = "LAST_1_DAY",
	LAST_3_DAYS = "LAST_3_DAYS",
	LAST_7_DAYS = "LAST_7_DAYS",
	LAST_14_DAYS = "LAST_14_DAYS",
	LAST_30_DAYS = "LAST_30_DAYS",
	LAST_60_DAYS = "LAST_60_DAYS",
	PREVIOUS_SEASON = "PREVIOUS_SEASON",
	TWO_SEASONS_AGO = "TWO_SEASON_AGO",
	THREE_SEASONS_AGO = "THREE_SEASON_AGO",
	ALL_TIME = "ALL_TIME",
	ARENA_EVENT = "ARENA_EVENT",
	CURRENT_EXPANSION = "CURRENT_EXPANSION",
	CURRENT_PATCH = "CURRENT_PATCH",
}

export const enum RankRange {
	TOP_1000_LEGEND = "TOP_1000_LEGEND",
	LEGEND_ONLY = "LEGEND_ONLY",
	LEGEND_THROUGH_FIVE = "LEGEND_THROUGH_FIVE",
	LEGEND_THROUGH_TEN = "LEGEND_THROUGH_TEN",
	LEGEND_THROUGH_TWENTY = "LEGEND_THROUGH_TWENTY",
	ALL = "ALL",
}
