# Generated by Django 2.0.4 on 2018-04-18 10:46

import django.db.models.deletion
import django.utils.timezone
import django_intenum
import hearthstone.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decks', '0018_clustersetsnapshot_promoted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchetypeName',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('player_class', django_intenum.IntEnumField(default=0, enum=hearthstone.enums.CardClass)),
                ('contributing_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchetypeSuggestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.Deck')),
                ('suggested_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.ArchetypeName')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='archetypesuggestion',
            unique_together={('deck', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='archetypename',
            unique_together={('name', 'player_class')},
        ),
    ]
