# Generated by Django 2.1.2 on 2018-10-17 19:59

import django.contrib.postgres.fields.jsonb
import django_intenum
import hearthstone.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0019_archetype_naming'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='required_cards',
            field=models.ManyToManyField(to='cards.Card'),
        ),
        migrations.AddField(
            model_name='clustersnapshot',
            name='required_cards',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
