
# Generated by Django 2.1.2 on 2018-10-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0020_archetype_required_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='required_cards',
            field=models.ManyToManyField(blank=True, to='cards.Card'),
        ),
    ]
